### ISSUE TITLE
关于抖音评论UI的实现，有几个问题请教哈你

### ISSUE THREAD

**Issue by yanmingLiu** [0x1306a94/SampleCode#1]
你好，我是看你博客里面关于抖音评论UI的实现，有几个问题请教哈你，谢谢！

https://blog.0x1306a94.com/docs/ios/ui/ch01/01/

1. Lookin是需要源码编译起来才能查看的哇，这个代码哪里抓的呢， 能否给我一个我研究一波哇？

2. 有tabbar情况下，就算是addSubView 也会在tabbar之下的哇，这里是如何处理的呢？
   我录屏抖音，然后看他的评论弹出的时候，tabbar并没有隐藏的。
AWECommentListViewController 为评论弹层, AWECommentListViewController 并未采用 addChildViewController 方式加入 AWEFeedContainerViewController 作为其 childViewController, 而是直接将 AWECommentListViewController.view 添加到 AWEFeedRootViewController.view

![Kapture 2021-08-19 at 19 43 06](https://user-images.githubusercontent.com/19849661/130063112-d2323b17-e455-477d-8915-4086fc53939d.gif)

**Comment by Dannyzheng831** [comment]
> 你好，我是看你博客里面关于抖音评论UI的实现，有几个问题请教哈你，谢谢！
> 
> https://blog.0x1306a94.com/docs/ios/ui/ch01/01/
> 
> 1. Lookin是需要源码编译起来才能查看的哇，这个代码哪里抓的呢， 能否给我一个我研究一波哇？
> 2. 有tabbar情况下，就算是addSubView 也会在tabbar之下的哇，这里是如何处理的呢？
>    我录屏抖音，然后看他的评论弹出的时候，tabbar并没有隐藏的。
>    AWECommentListViewController 为评论弹层, AWECommentListViewController 并未采用 addChildViewController 方式加入 AWEFeedContainerViewController 作为其 childViewController, 而是直接将 AWECommentListViewController.view 添加到 AWEFeedRootViewController.view
> 
> ![Kapture 2021-08-19 at 19 43 06](https://user-images.githubusercontent.com/19849661/130063112-d2323b17-e455-477d-8915-4086fc53939d.gif)

请教大神，这两个问题您有答案了吗

**Comment by 0x1306a94** [comment]
* [Lookin](https://lookin.work/)
* 想要在`tabBar`上面, 可以通过添加到 `tabBarController.view` 或者 自定义 `Present`, 再或者加到`keyWindow`

**Comment by 0x1306a94** [comment]
@Dannyzheng831 @yanmingLiu 

* [Lookin](https://lookin.work/)
* 想要在`tabBar`上面, 可以通过添加到 `tabBarController.view` 或者 自定义 `Present`, 再或者加到`keyWindow`

**Comment by yanmingLiu** [comment]
> > 你好，我是看你博客里面关于抖音评论UI的实现，有几个问题请教哈你，谢谢！
> > https://blog.0x1306a94.com/docs/ios/ui/ch01/01/
> > 
> > 1. Lookin是需要源码编译起来才能查看的哇，这个代码哪里抓的呢， 能否给我一个我研究一波哇？
> > 2. 有tabbar情况下，就算是addSubView 也会在tabbar之下的哇，这里是如何处理的呢？
> >    我录屏抖音，然后看他的评论弹出的时候，tabbar并没有隐藏的。
> >    AWECommentListViewController 为评论弹层, AWECommentListViewController 并未采用 addChildViewController 方式加入 AWEFeedContainerViewController 作为其 childViewController, 而是直接将 AWECommentListViewController.view 添加到 AWEFeedRootViewController.view
> > 
> > ![Kapture 2021-08-19 at 19 43 06](https://user-images.githubusercontent.com/19849661/130063112-d2323b17-e455-477d-8915-4086fc53939d.gif)
> 
> 请教大神，这两个问题您有答案了吗

有了 ， 去看我实现。https://github.com/yanmingLiu/swift5DouYin
